FROM nginx
COPY project.conf /etc/nginx/conf.d/default.conf

# FROM nginx:stable-alpine

# #RUN rm /etc/nginx/default.conf

# COPY nginx.conf /etc/nginx/nginx.conf

# FROM nginx:1.15.8

# # RUN rm /etc/nginx/nginx.conf
# # COPY nginx.conf /etc/nginx/
# # RUN rm /etc/nginx/conf.d/default.conf
# COPY project.conf /etc/nginx/conf.d/default.conf